// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: internal/proto/schema.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoggAggregator_Log_FullMethodName      = "/svarog.LoggAggregator/Log"
	LoggAggregator_BatchLog_FullMethodName = "/svarog.LoggAggregator/BatchLog"
)

// LoggAggregatorClient is the client API for LoggAggregator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Interface exported by the server.
type LoggAggregatorClient interface {
	Log(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogLine, Void], error)
	BatchLog(ctx context.Context, in *Backlog, opts ...grpc.CallOption) (*Void, error)
}

type loggAggregatorClient struct {
	cc grpc.ClientConnInterface
}

func NewLoggAggregatorClient(cc grpc.ClientConnInterface) LoggAggregatorClient {
	return &loggAggregatorClient{cc}
}

func (c *loggAggregatorClient) Log(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogLine, Void], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LoggAggregator_ServiceDesc.Streams[0], LoggAggregator_Log_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogLine, Void]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LoggAggregator_LogClient = grpc.ClientStreamingClient[LogLine, Void]

func (c *loggAggregatorClient) BatchLog(ctx context.Context, in *Backlog, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, LoggAggregator_BatchLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoggAggregatorServer is the server API for LoggAggregator service.
// All implementations must embed UnimplementedLoggAggregatorServer
// for forward compatibility.
//
// Interface exported by the server.
type LoggAggregatorServer interface {
	Log(grpc.ClientStreamingServer[LogLine, Void]) error
	BatchLog(context.Context, *Backlog) (*Void, error)
	mustEmbedUnimplementedLoggAggregatorServer()
}

// UnimplementedLoggAggregatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoggAggregatorServer struct{}

func (UnimplementedLoggAggregatorServer) Log(grpc.ClientStreamingServer[LogLine, Void]) error {
	return status.Errorf(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedLoggAggregatorServer) BatchLog(context.Context, *Backlog) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchLog not implemented")
}
func (UnimplementedLoggAggregatorServer) mustEmbedUnimplementedLoggAggregatorServer() {}
func (UnimplementedLoggAggregatorServer) testEmbeddedByValue()                        {}

// UnsafeLoggAggregatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoggAggregatorServer will
// result in compilation errors.
type UnsafeLoggAggregatorServer interface {
	mustEmbedUnimplementedLoggAggregatorServer()
}

func RegisterLoggAggregatorServer(s grpc.ServiceRegistrar, srv LoggAggregatorServer) {
	// If the following call pancis, it indicates UnimplementedLoggAggregatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoggAggregator_ServiceDesc, srv)
}

func _LoggAggregator_Log_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LoggAggregatorServer).Log(&grpc.GenericServerStream[LogLine, Void]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LoggAggregator_LogServer = grpc.ClientStreamingServer[LogLine, Void]

func _LoggAggregator_BatchLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Backlog)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggAggregatorServer).BatchLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoggAggregator_BatchLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggAggregatorServer).BatchLog(ctx, req.(*Backlog))
	}
	return interceptor(ctx, in, info, handler)
}

// LoggAggregator_ServiceDesc is the grpc.ServiceDesc for LoggAggregator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoggAggregator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "svarog.LoggAggregator",
	HandlerType: (*LoggAggregatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BatchLog",
			Handler:    _LoggAggregator_BatchLog_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Log",
			Handler:       _LoggAggregator_Log_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "internal/proto/schema.proto",
}
