// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: internal/proto/schema.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Void struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Void) Reset() {
	*x = Void{}
	mi := &file_internal_proto_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_internal_proto_schema_proto_rawDescGZIP(), []int{0}
}

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        string                 `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sequence      int64                  `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_internal_proto_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_internal_proto_schema_proto_rawDescGZIP(), []int{1}
}

func (x *LogLine) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *LogLine) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogLine) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogLine) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type Backlog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*LogLine             `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Backlog) Reset() {
	*x = Backlog{}
	mi := &file_internal_proto_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backlog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backlog) ProtoMessage() {}

func (x *Backlog) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backlog.ProtoReflect.Descriptor instead.
func (*Backlog) Descriptor() ([]byte, []int) {
	return file_internal_proto_schema_proto_rawDescGZIP(), []int{2}
}

func (x *Backlog) GetLogs() []*LogLine {
	if x != nil {
		return x.Logs
	}
	return nil
}

var File_internal_proto_schema_proto protoreflect.FileDescriptor

const file_internal_proto_schema_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/proto/schema.proto\x12\x06svarog\x1a\x1fgoogle/protobuf/timestamp.proto\"\x06\n" +
	"\x04Void\"\x91\x01\n" +
	"\aLogLine\x12\x16\n" +
	"\x06client\x18\x01 \x01(\tR\x06client\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x03R\bsequence\".\n" +
	"\aBacklog\x12#\n" +
	"\x04logs\x18\x01 \x03(\v2\x0f.svarog.LogLineR\x04logs2g\n" +
	"\x0eLoggAggregator\x12(\n" +
	"\x03Log\x12\x0f.svarog.LogLine\x1a\f.svarog.Void\"\x00(\x01\x12+\n" +
	"\bBatchLog\x12\x0f.svarog.Backlog\x1a\f.svarog.Void\"\x00B#Z!github.com/markojerkic/svarog/rpcb\x06proto3"

var (
	file_internal_proto_schema_proto_rawDescOnce sync.Once
	file_internal_proto_schema_proto_rawDescData []byte
)

func file_internal_proto_schema_proto_rawDescGZIP() []byte {
	file_internal_proto_schema_proto_rawDescOnce.Do(func() {
		file_internal_proto_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_schema_proto_rawDesc), len(file_internal_proto_schema_proto_rawDesc)))
	})
	return file_internal_proto_schema_proto_rawDescData
}

var file_internal_proto_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_proto_schema_proto_goTypes = []any{
	(*Void)(nil),                  // 0: svarog.Void
	(*LogLine)(nil),               // 1: svarog.LogLine
	(*Backlog)(nil),               // 2: svarog.Backlog
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_internal_proto_schema_proto_depIdxs = []int32{
	3, // 0: svarog.LogLine.timestamp:type_name -> google.protobuf.Timestamp
	1, // 1: svarog.Backlog.logs:type_name -> svarog.LogLine
	1, // 2: svarog.LoggAggregator.Log:input_type -> svarog.LogLine
	2, // 3: svarog.LoggAggregator.BatchLog:input_type -> svarog.Backlog
	0, // 4: svarog.LoggAggregator.Log:output_type -> svarog.Void
	0, // 5: svarog.LoggAggregator.BatchLog:output_type -> svarog.Void
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_proto_schema_proto_init() }
func file_internal_proto_schema_proto_init() {
	if File_internal_proto_schema_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_schema_proto_rawDesc), len(file_internal_proto_schema_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_schema_proto_goTypes,
		DependencyIndexes: file_internal_proto_schema_proto_depIdxs,
		MessageInfos:      file_internal_proto_schema_proto_msgTypes,
	}.Build()
	File_internal_proto_schema_proto = out.File
	file_internal_proto_schema_proto_goTypes = nil
	file_internal_proto_schema_proto_depIdxs = nil
}
