tmp_dir = "build"
rum_cmd = "build/server"

[build]
    cmd = "make build-dev"
    bin = "./build/server"
    exclude_regex = ["_test.go", ".*_templ.go", "build/.*", "web/*"]
    exclude_dir= ["build", "web"]
    include_ext = ["go", "tpl", "tmpl", "templ", "html", "css"]
