include:
  - docker-compose.dev.yml

services:
  svarog:
    image: markojerkic/svarog:latest
    container_name: svarog
    build:
      context: .
      dockerfile: ./cmd/server/Dockerfile
    ports:
      - 1324:1323
    environment:
      - SVAROG_CONN_STRING=${SVAROG_CONN_STRING}
      - MONGO_URL=mongodb://svarog-mongodb:27017/?directConnection=true
      - SESSION_SECRET=${SESSION_SECRET}
      - HTTP_SERVER_PORT=1323
      - NATS_PUBLIC_ADDR=localhost:4222
      - NATS_ADDR=nats://nats:4222
      - NATS_ACCOUNT_SEED=${NATS_ACCOUNT_SEED}
      - NATS_SERVER_USER_JWT=${NATS_SERVER_USER_JWT}
      - NATS_SERVER_USER_SEED=${NATS_SERVER_USER_SEED}
      - NATS_ACCOUNT_PUBLIC_KEY=${NATS_ACCOUNT_PUBLIC_KEY}
    depends_on:
      - svarog-mongodb
      - nats
    develop:
      watch:
        - path: .
          target: builder
          action: rebuild
