# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  reset-db:
    desc: Resets the database and nats
    cmds:
      - docker compose  -f docker-compose.dev.yml down -v

  db:
    desc: Starts the database and nats
    cmds:
      - docker compose --env-file .env -f docker-compose.dev.yml up -d

  tailwind:
    desc: Watch Tailwind CSS changes
    cmds:
      - bun run tw

  templ:
    desc: Run templ with integrated server and hot reload
    cmds:
      - templ generate --watch --proxy="http://localhost:1323" --cmd="go run cmd/server/main.go" --open-browser=false

  dev:
    desc: Start development server with hot reload
    deps:
      - db
    cmds:
      - task --parallel templ tailwind

  clean-tmp:
    desc: Clean Go temporary build files from /tmp
    cmds:
      - find /tmp -maxdepth 1 -name "go-build*" -exec rm -rf {} +
      - echo "Cleaned /tmp/go-build* directories"

  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.TAILWIND_CMD}}"
    silent: true
