# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  test:watch:
    desc: Run tests in watch mode
    watch: true
    sources:
      - "**/*.go"
    cmds:
      - go test {{.CLI_ARGS}}

  reset-db:
    desc: Resets the database and nats
    cmds:
      - docker compose  -f docker-compose.dev.yml down -v

  db:
    desc: Starts the database and nats
    cmds:
      - docker compose --env-file .env -f docker-compose.dev.yml up -d

  tailwind:
    desc: Watch Tailwind CSS changes
    cmds:
      - bun run tw

  templ:
    desc: Run templ with integrated server and hot reload
    cmds:
      - go tool templ generate --watch --proxy="http://localhost:1323" --cmd="go run cmd/server/main.go" --open-browser=false

  dev:
    desc: Start development server with hot reload
    deps:
      - db
    cmds:
      - task --parallel templ tailwind

  clean-tmp:
    desc: Clean Go temporary build files from /tmp
    cmds:
      - find /tmp -maxdepth 1 -name "go-build*" -exec rm -rf {} +
      - echo "Cleaned /tmp/go-build* directories"

  docker:client:
    desc: Build the client Docker image
    cmds:
      - docker build --progress=plain -t svarog-client:{{.SVAROG_VERSION | default "latest"}} -f cmd/client/Dockerfile .

  docker:server:
    desc: Build the server Docker image
    cmds:
      - docker build --progress=plain -t svarog:{{.SVAROG_VERSION | default "latest"}} -f cmd/server/Dockerfile .

  docker:build:
    desc: Build both Docker images in parallel
    cmds:
      - task --parallel --output=prefixed docker:client docker:server

  default:
    desc: Build the Docker images
    cmds:
      - task docker:build
    silent: true
