name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22.x' ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go ${{ matrix.go-version }}  
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache: true

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Install Bun dependencies
      run: bun install
      working-directory: ./web

    - name: Run Go tests
      run: make test-server

    - name: Run Bun tests
      run: make test-web
